### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by almandin** [moloch--/leakdb#1]
Hi there,
I try to use your tool and struggle after the normalization process.

Your doc suggests to use a command like that `$> leakdb-curator --json file.json` but it doesnt work, the program returns `Applying bloom filter ...[!] open file.json: not a directory`.
Il looks that the doc is missing just a word/flag/command on your example to work :)

Thanks by advance.

**Comment by moloch--** [comment]
You should be able to pass the `--json` file directly to the main command (which automates all of the subcommands). Ensure your `file.json` exists, it should be able to accept a single file or directory of files.

The following command works for me:

```
moloch@atlas ~/l/normalized> ./leakdb-curator --json test.json
Applying bloom filter ...
   Uniques = 601836 (263747/sec)
Duplicates = 326
```

If you're still having issues can you let me know what OS/build you're using?

**Comment by almandin** [comment]
Ok I get it, when you download a release, you have a zip file containing 3 files, one is called "leakdb". When you call `leakdb-curator` from the command line, it tries to create a folder named `leakdb` to put output files into it. Bad luck, the `leakdb` binary already exists ...

**Comment by almandin** [comment]
`/internal/curator/main.go:182`, a folder named "leakdb" is created. I think other people will have the same problem if you dont change the name of the default output folder :p

**Comment by moloch--** [comment]
oh that's a good point, I hadn't thought of haha. I'll add some code to check if the file/directory exists.
